config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  resources :activities
  patch 'activities/increase_priority/:id', to: 'activities#increase_priority',
  as: 'activity_increase_priority'
  patch 'activities/decrease_priority/:id', to: 'activities#decrease_priority',
  as: 'activity_decrease_priority'

end

app/models/activity.rb
class Activity < ApplicationRecord

  before_save :assign_priority, if: :first_time?

  validates :name, presence: true

  UP_PRIORITY = "up"
  DOWN_PRIORITY = "down"


  # priority is an attribute invisible to the user

  # TODO: Será que pode copiar o valor do id para priority ?
  # Assim que salvasse (after_save), pegava o id, atribuía e dava um update
  # no objeto
  def assign_priority
    self.priority = biggest_priority + 1
  end

  def first_time?
    self.id.nil?
  end

  def self.all_for_priority_asc
  	Activity.all.order(priority: :asc)
  end

  def self.all_for_priority_desc
  	Activity.all.order(priority: :desc)
  end

  def self.all_for_created_at_desc
  	Activity.all.order(created_at: :desc)
  end

  def change_priority(kind)
    unless kind != UP_PRIORITY and kind != DOWN_PRIORITY
      
      if kind == UP_PRIORITY
        activity_database = Activity.order(priority: :desc).
          where("priority < ?", self.priority).first
      elsif kind == DOWN_PRIORITY
        activity_database = Activity.order(priority: :asc).
          where("priority > ?", self.priority).first
      end

      unless activity_database.nil?
        priority_database = activity_database.priority
        object_priority = self.priority

        Activity.transaction do
          activity_database.update(priority: -1)
          self.update(priority: priority_database)
          activity_database.update(priority: object_priority)
        end
      end

    end

  end



  private

    def biggest_priority
      activities = Activity.all_for_priority_desc
      if not activities.empty?
        activities.select(:priority).first.priority
      else
        -1
      end
    end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to @activity
    else
      render "new"
    end
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def index
    @activities = Activity.all_for_priority_asc
  end

  def increase_priority
    @activity = Activity.find(params[:id])
    @activity.change_priority(Activity::UP_PRIORITY)

    respond_to do |format|
      format.js
      format.json { render json: @activity, layout: false, status: :ok, location: @activity }
    end
  end

  def decrease_priority
    @activity = Activity.find(params[:id])
    @activity.change_priority(Activity::DOWN_PRIORITY)

    puts "pirioidade " + Activity::DOWN_PRIORITY

    respond_to do |format|
      format.js
      format.json { render json: @activity, layout: false, status: :ok, location: @activity }
    end
  end

  private
    def activity_params
      params.require(:activity).permit(:name, :description, :period)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/decrease_priority.js.erb
jQuery("#activity_row_<%= @activity.id %>").next().after(jQuery("#activity_row_<%= @activity.id %>"));

app/views/activities/increase_priority.js.erb
jQuery("#activity_row_<%= @activity.id %>").prev().before(jQuery("#activity_row_<%= @activity.id %>"));

app/views/activities/index.html.erb
<h1>Atividades</h1>

<table class="table table-striped">
<thead>
	<tr>
		<th style="width: 4%"></th>
		<th>Ordem</th>
		<th>Nome</th>
		<th>Descrição</th>
		<th style="text-align: center;">Período</th>
	</tr>
</thead>
<tbody>
	<% @activities.each_with_index do |activity, i| %>
		<tr id="activity_row_<%= activity.id %>">
			<td>
				<%= link_to(activity_increase_priority_path(activity), remote: true, method: 'patch') do %>
				    <span class="glyphicon glyphicon-chevron-up" style="cursor: pointer;" title="Aumentar prioridade"/>
				<% end %>

				<%= link_to(activity_decrease_priority_path(activity), remote: true, method: 'patch') do %>
				    <span class="glyphicon glyphicon-chevron-down" style="cursor: pointer;" title="Diminuir prioridade" />
				<% end %>

			</td>
			<td style="width: 5%; text-align: center;"><%= i + 1 %></td>
			<td style="width: 20%;"><%= link_to activity.name, activity_path(activity.id) %></td>
			<td style="width: 55%;"><%= raw activity.description %></td>
			<td style="text-align: center;"><%= activity.period %></td>
		</tr>
	<% end %>
</tbody>
<tfoot>
	<tr>
		<td colspan="5">
			<%= link_to 'Voltar', root_path, class: "btn btn-primary" %>
		</td>
	</tr>
</tfoot>
</table>

<script type="text/javascript">
	$(document).ready(function() {
	  $(function(){
	    // $.getJSON('/activity_increase_priority/increase_priority.json', function(data1) {
	     // alert("inside getJson"); alert(data1); console.log(data1);
	    // });
	});
	});
</script>

app/views/activities/new.html.erb
<h2>Cadastrar Atividade</h2>
<br/>

<% if @activity.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@activity.errors.count, "error") %> 
    </h2>
    <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<br/>
<br/>

<%= form_for @activity, :html => {:class => 'form form-horizontal'} do |f| %>

  <div class="form-group">
    <label for="" class="col-sm-2 control-label"><%= t('activerecord.attributes.activity.name') + ':' %></label>
    <div class="col-sm-10">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="form-group">
    <label for="" class="col-sm-2 control-label"><%= f.label :period, "Período" %></label>
    <div class="col-sm-10">
      <%= f.text_field :period %>
    </div>
  </div>
  <div class="form-group">
    <label for="" ><%= f.label :description, "Descrição" %></label>
      <%= f.text_area :description, class: "formatting" %>
  </div>
  <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
   <i class="icon-ok icon-white"></i> Cadastrar
  <% end %>
<% end %>


app/views/activities/show.html.erb
<h1>Atividade</h1>
<br/>
<p>
  <strong>Nome:</strong>
  <%= @activity.name %>
</p>
<p>
  <strong>Período:</strong>
  <%= @activity.period %>
</p>
<p>
  <strong>Descrição:</strong>
  <%= raw @activity.description %>
</p>

app/views/activities/test.js.erb
var up_row = $("#activity_row_<%= @activity.priority %>").prev();
$("#activity_row_<%= @activity.priority %>").prev().remove();
$("#activity_row_<%= @activity.priority %>").after(up_row);

$("<%= escape_javascript(render @activity) %>").appendTo("#activity_row_0");


$('#activity_row_0').append('<%= j render 'activity', activity: @activity %>')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cronograma De Estudos</title>
    <%= csrf_meta_tags %>
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container container-fluid">
	  	<div class="row">
	  		<div class="col-md-12"><%= yield %></div>
	  	</div>
  	</div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Cronograma de Estudos</h1>

<h2>Atividades</h2>
<ul>
	<li><%= link_to 'Cadastrar', new_activity_path %></li>
	<li><%= link_to 'Listar', activities_path %></li>
</ul>